### ISSUE TITLE
'Readme' not up to date

### ISSUE THREAD

**Issue by CharStephens** [ably/ably-go#112]
It's been flagged that the readme for the go lib is not up to date

**Comment by paddybyers** [comment]
The reported issue is:

> the final line of code under 'Creating a client' is apparently wrong, should it read `channel := client.Channel("test")`

**Comment by mattheworiordan** [comment]
@paddybyers is this an issue?  The spec for the API is `client.Channels.Get("test")` not `client.Channel("test")`
