### ISSUE TITLE
Support client instantiation via Token or TokenRequest

### ISSUE THREAD

**Issue by kouno** [ably/ably-go#12]
On the REST and Realtime library.

/!\ Do not implement this yet as some discussion are going on about the naming convention for Token and TokenRequest.

Our client libraries are still not in line with each other on that point.

**Comment by mattheworiordan** [comment]
FYI, see https://github.com/ably/ably-js/issues/33

**Comment by rjeczalik** [comment]
ACK

**Comment by rjeczalik** [comment]
Done by #19 with PR #22. Can be closed.
