### ISSUE TITLE
HTTPPaginatedResult and PaginatedResult are missing some methods

### ISSUE THREAD

**Issue by tomczoink** [ably/ably-go#120]
It appears https://github.com/ably/ably-go/blob/develop/ably/http_paginated_response.go is missing various methods, such as `IsLast`, `HasNext` and `First`. They should have these methods to match the other libraries.

Once added, we need to also re-add these methods to the docs. Currently they are commented out with the indicator `GO_REPLACEMENT` to easily find and uncomment them.

┆sprint: SDK 2022-Q1-S6

**Comment by mattheworiordan** [comment]
See https://github.com/ably/ably-go/pull/104

This PR added `request` functionality, which was not complete :/
