### ISSUE TITLE
Remove develop branch

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-go#128]
We are modifying all repositories to just have a `master` branch, removing `develop`, inline with our updated development flow / branching strategy (internally documented for now but [will be added to docs soon](https://github.com/ably/docs/issues/577)).

This might involve:
- Updating references to `develop` branch in this repository
- Reconfiguring CI systems that rely upon `develop`

**Comment by paddybyers** [comment]
I've updated the default branch in github to `master`, and updated the README to reflect that. Travis just gets the default branch from github, so afaik there's nothing further to do. 

I have not deleted `develop` from github yet, in case anyone has tooling that depends on it.

**Comment by QuintinWillison** [comment]
I'm going to delete `develop` now. If anybody shouts, worst case, we can restore.
