### ISSUE TITLE
Avoid message bundling, conforming to updated RTL6d

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-go#133]
See [RTL6d](https://docs.ably.io/client-lib-development-guide/features/#RTL6d), as amended by this [docs PR](https://github.com/ably/docs/pull/788#issuecomment-581490475).

There may be no work to do if this client library already doesn't bundle messages, however I've not got time to investigate that right now so am creating the issue so that investigation can take place followed by remediation if required.

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-141) by [Unito](https://www.unito.io)
┆sprint: SDK 2022-Q2-S7  23/06

**Comment by QuintinWillison** [comment]
For reference, see the equivalent [ably-js issue](https://github.com/ably/ably-js/issues/629) which includes commentary describing how it had already been resolved and a link to the [relevant pull request](https://github.com/ably/ably-js/pull/623).

**Comment by mohyour** [comment]
Ably-go seem not to bundle messages. Will be closing this as it's not needed
