### ISSUE TITLE
Can the ablytest.Sandbox provide an Ably Token to authenticate with?

### ISSUE THREAD

**Issue by audiolion** [ably/ably-go#140]
Looking into the ablytest.Sandbox, it provides a `Key` method that returns a valid api key for the short-lived sandbox. Is there a way to have the Sandbox return a valid Ably Token? I saw that there is a ReverseAuthProxy in the ablytest package that contains a `/details` endpoint that returns token details. I am not sure how to use that in conjunction with the Sandbox though so that it can provide Ably Tokens.

**Comment by QuintinWillison** [comment]
Hello @audiolion - I'm going to assign this to @tcard to give you a fuller response when he's able as my knowledge in this area not great. In lieu of Toni's response, have you been consulted the following areas of the client library development guide, and if not then may they be of use to you?

- [Sandbox Test API](https://docs.ably.io/client-lib-development-guide/test-api/)
- [Request an access token (REST API)](https://docs.ably.io/rest-api/#request-token)

**Comment by audiolion** [comment]
Ok I think that is where I was going towards. Setup the Sandbox and make a rest client that asks for an ably access token. I will give that a try.

**Comment by tcard** [comment]
@audiolion That's the way to go, yes. You can use `rest.auth.requestToken` to get a token.

Keys are fixed because they cannot be generated on-the-fly, as tokens can, as well as to give you "admin" access to the just created app for as long as the app exists.

**Comment by tcard** [comment]
I'll tentatively close this, but @audiolion please tell us if this doesn't solve your problem and we'll reopen.

**Comment by audiolion** [comment]
Hey @tcard,

Followed advice to use `rest.Auth.RequestToken`, it seems to be working, except my realtime client established with the token never transitions from `ably.StateConnConnecting` to `ably.StateConnConnected` and instead moves to `ably.StateConnFailed`. Below are some debug traces I did:

New sandbox:
![image](https://user-images.githubusercontent.com/2430381/78419617-6f2f8f00-7615-11ea-9a7d-af2fa2a14600.png)

token details:
![image](https://user-images.githubusercontent.com/2430381/78419624-82425f00-7615-11ea-8c8e-87ade170025d.png)

failure message in `eventloop()`:
![image](https://user-images.githubusercontent.com/2430381/78419631-a0a85a80-7615-11ea-8c50-1f145d51462f.png)

I don't really understand what is wrong because as you can see from sandbox appid, token details app id, and failure message app id, they all line up correctly. Is there some permission issue? The token seems to have all capabilities so it seems unlikely.

Reproducible example:

```go
import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/ably/ably-go/ably"
	"github.com/ably/ably-go/ably/ablytest"
)

func TestRouter(t *testing.T) {
	app, restClient := ablytest.NewRestClient(nil)

	ts := httptest.NewServer(
		http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			authHeader := r.Header.Get("Authorization")
			if authHeader == "" {
				w.WriteHeader(http.StatusUnauthorized)
				return
			}

			if r.URL.Path != "/issue-token-request" {
				w.WriteHeader(http.StatusNotFound)
				return
			}

			tok, err := restClient.Auth.RequestToken(&ably.TokenParams{ClientID: authHeader}, nil)
			if err != nil {
				t.Error(err)
				return
			}

			respData, err := json.Marshal(tok)
			if err != nil {
				t.Error(err)
				return
			}

			w.Header().Add("Content-Type", "application/json")
			w.Write(respData)
		}),
	)

	headers := http.Header{}
	headers.Add("Authorization", "*")

	client, err := ably.NewRealtimeClient(&ably.ClientOptions{
		AuthOptions: ably.AuthOptions{
			AuthMethod:  "POST",
			AuthURL:     ts.URL + "/issue-token-request",
			AuthHeaders: headers,
		},
	})
	if err != nil {
		t.Fatal(err)
	}

	channel := client.Channels.Get("test")

        // this will timeout after 30s, client connection transitions from Connecting to Failed
	if err := ablytest.Wait(channel.Publish("foo", "bar")); err != nil {
		t.Fatal(err)
	}

	t.Cleanup(func() {
		if err := app.Close(); err != nil {
			t.Error(err)
		}
		ts.Close()
	})
}
```

**Comment by paddybyers** [comment]
@audiolion thanks for reporting this. We'll have a look

**Comment by tcard** [comment]
@audiolion It seems to be you need to tell your `client` that it must use the sandbox environment, like this:

```go
client, err := ably.NewRealtimeClient(&ably.ClientOptions{
		Environment: "sandbox",
```

`ablytest.NewRestClient` creates an app in the sandbox environment, while the client below tries to use that app in the default (production) environment, hence the 404.

Please tell us if the issue persist.

**Comment by audiolion** [comment]
Ah that makes sense. I forgot the URL is derived from the environment.
