### ISSUE TITLE
Implementing reauthentication before or after token expires

### ISSUE THREAD

**Issue by audiolion** [ably/ably-go#153]
Hello 👋 ,

I am using the `ably.NewRealtimeClient` and wondering if I could get some guidance as to how reauthentication should work when the ably token expires. Currently I am using the AuthURL/AuthHeaders method to have ably request a token from one of our servers and the token expires in an hour.

**Comment by audiolion** [comment]
To expand upon this I want to share what I have currently tested out.

When I create my realtime client, I register a `client.Connection.On()` handler and listen for `ably.StateDisconnected` events. When I receive that event, I call `client.Auth.Authorize()` which requests a new token, and then `client.Connection.Connect()`. Upon reconnection, I have to reattach my channels which moved to an `ably.StateChanFailed` state when the client disconnected. I call `client.Channels.Get()` to get all channels and range over them calling `channel.Attach()` on each one which moves them to `Attaching`, then `Attached` state again. At this point, any messages sent are missed. The only thing I can think of to solve this is to use the Rest API to query for history and grab messages with timestamps after the ably connection disconnected and reprocess them.

The whole snippet looks like:

```go
stateCh := make(chan ably.State)
client.Connection.On(stateCh)
for state := range stateCh {
  if state.State == ably.StateConnDisconnected {
    _, err := client.Auth.Authorize(nil, nil)
    res, err := client.Connection.Connect()
    err = res.Wait()
    for channel := range client.Channels.Get() {
      channel.Attach()
      rst, err := channel.History()
      for msg := rst.Messages() {
        if msg.Timestamp >= lastDisconnectAt {
          // reprocess msg
        }
      }
    }
  }
}
```

Is there a better way to go about this with 0.8? Is there any way to refresh the token before it expires so we don't send brief presence exit/enter messages every time the token expires?

**Comment by tcard** [comment]
Hi @audiolion. Unfortunately, right now what you posted is the best you can do.

Client libraries are supposed to automatically reauthenticate and recover the connection state so as not to lose messages nor channel presence. But this library doesn't support that yet. We're working on having this implemented as soon as possible.

**Comment by audiolion** [comment]
@tcard appreciate the quick response. I know you all are working on it, and saw Ably recently raised a round of funding too, exciting! We will proceed forward as-is then, since reconnect is very fast (<5s, most of the time a 100ms), our band-aid is to kick off a background job when presence goes offline that triggers 10s later so that we don't blip on/off with presence every hour when the token expires.

Looking forward to the 1.1/1.2 spec features though!
