### ISSUE TITLE
Subscribe(), Attach() are either counterintuitive or broken

### ISSUE THREAD

**Issue by paddybyers** [ably/ably-go#155]
An attach error - such as a permissions error - is not returned in the `err` return value from either `Attach()` or `Subscribe()`. An error from the `Send()` of the `ATTACH` message would be returned, but `Attach()` does not wait for the `ATTACHED` response, and so it cannot return any error in from response.

**Comment by tcard** [comment]
`Attach` returns a `Result`, which the you can call `Wait` on to wait for ATTACHED and get the error.

This is very unidiomatic and we'll get rid of it. Return types annotated as `io` in the spec will just be sync. That's the idiomatic way in Go (if you don't want to wait, you spawn a goroutine).

**Comment by Rosalita** [comment]
Verified in `v1.2.3` that `attach()`, `subscribe()` and `subscribeAll()` can all return an error without having to make a call to `result.Wait()`. Closing as fixed.
