### ISSUE TITLE
Reauthentication with Presence

### ISSUE THREAD

**Issue by audiolion** [ably/ably-go#164]
Having some troubles with presence in the ably-go client being incorrect when restarting and reauthenticating. The flow is:

```
-> Initial connection to Ably
-> Presence message online fires for client
-> Kill program
<- Ably server sees the client disconnected, waits for 30s for it to recover
-> Start program
-> New connection to Ably
-> Presence message online fires for client
<- Ably after 30s of not recovering the initial connection to Ably sends Offline presence event

=> client now appears offline even though it has an ably connection
```

Something similar also appears to happen when the authentication token expires, we immediately reauthenticate, but Ably sets us as offline. I am not sure in this case if ably immediately sets the client offline when the token expires, or waits 30s. I am also not sure when we reauthenticate with a refreshed token if a presence online message is fired.

**Comment by audiolion** [comment]
Ok did some more research, I did not fully understand the presence association with channels and having multiple `connectionId`s for the same `clientId` on a channel.

I think this is something we can solve on our API side, to only listen for presence events from the most recently created `connectionId`. That way when we restart the program or reconnect, we can ignore the message that says offline for the old connection ID when it times out attempting to reconnect after 30s.

Going to leave this open just in case I have gotten something fundamentally wrong in my understanding here. I guess the only problem will be if our API doesn't have visibility into the connectionIds associated with the presence messages and when they were created.

**Comment by paddybyers** [comment]
Each member of a presence set is a `(connectionId, clientId)` pair. This is because there are lots of situations where the same user identity needs to be present multiple times (eg both from a phone and laptop). 

Reconnections of a single client ought to be handled because when resuming the connection should retain the same `connectionId` as before. However, if this isn't happening for some reason, you're going to see this effect where both members can be present simultaneously for a short period.

**Comment by audiolion** [comment]
Thanks for the quick response! I believe in the current spec of ably-go it creates a new connectionId because there is no method to do reauthentication. See #153 for more details, the gist of it is that we do a new authorization with a new token when the old token expires, which I believe is creating a new `(connectionId, clientId)` pair. Anyways, this understand has helped solve our presence issue by only considering the latest created `(connectionId, clientId)` pair, thanks!
