### ISSUE TITLE
Defaults: Generate environment fallbacks

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-go#198]
Per `RSC15g`, introduced in https://github.com/ably/docs/pull/965.

See https://github.com/ably/ably-js/pull/682 and https://github.com/ably/ably-ruby/pull/196 for reference implementations.

**Comment by sacOO7** [comment]
Other reference implementations
https://github.com/ably/ably-dotnet/pull/454
https://github.com/ably/ably-java/pull/618
https://github.com/ably/ably-js/pull/689
