### ISSUE TITLE
Fix REST/Presence tests to not fail randomly.

### ISSUE THREAD

**Issue by rjeczalik** [ably/ably-go#20]
Running all tests one after another causes Presence tests to fail sporadically. They started to be flaky after merging all ably-go packages into one.

Example output:

```
~ $ for j in "-race" ""; do for i in {1..10}; do go test $j ./...; done; done
(...)

[Fail] Presence tested against presence fixture data set up in test app Get [It] returns current members on the channel 
/Users/rjeczalik/ably/src/github.com/ably/ably-go/ably/rest_presence_test.go:25

[Fail] Presence tested against presence fixture data set up in test app Get with a limit option [It] returns a paginated response 
/Users/rjeczalik/ably/src/github.com/ably/ably-go/ably/rest_presence_test.go:32

[Fail] Presence tested against presence fixture data set up in test app History [It] returns a list of presence messages 
/Users/rjeczalik/ably/src/github.com/ably/ably-go/ably/rest_presence_test.go:50

[Fail] Presence tested against presence fixture data set up in test app History with start and end time [It] can return older items from a certain date given a start / end timestamp 
/Users/rjeczalik/ably/src/github.com/ably/ably-go/ably/rest_presence_test.go:63
```

**Comment by mattheworiordan** [comment]
@rjeczalik that is sad :(

The only way we can typically resolve issues is for us to see the actual HTTP request and responses from the REST API and then links to the test code.  If we have this information, we will be able to see immediately if the problem is with the realtime system or the library itself.  Can you do that for the above?

**Comment by rjeczalik** [comment]
@mattheworiordan I believe this is test code - Presence tests may interfere with other tests from the suite and given gingko test order randomisation I have random failures.

**Comment by mattheworiordan** [comment]
RSpec Ruby tests run in random order so I have no idea why that should have a bearing.  Also, the tests should be read-only so I am not sure how that could be effected i.e. the REST Presence tests are only against fixture data.

**Comment by rjeczalik** [comment]
> Also, the tests should be read-only so I am not sure how that could be effected i.e. the REST Presence tests are only against fixture data.

Ok, I'll dump requests/responses for passed and broken tests and diff them to see the difference.

**Comment by rjeczalik** [comment]
@mattheworiordan: I did not observe single test failure with #24; this PR refactors testApp a bit to return always a copy of `ClientOptions` for REST client; there're tests that do modify global instances of `client`, `channel`, `testApp.Options` and my hunch is for certain `seeds` tests were failing due to other overwriting the global shared resources for them. Just FYI, but I'm going to still look out for those failures.

**Comment by mattheworiordan** [comment]
Is this still happening, or can we close this issue?

**Comment by rjeczalik** [comment]
@mattheworiordan No, these tests are not a problem anymore, since then they were rewritten to use multiple sandbox objects per group of tests. Current state of testing can be tracked in this issue #47.
