### ISSUE TITLE
Spec validation

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-go#31]
For version 0.8 of our client libraries, we have a documented specification at http://docs.ably.io/client-lib-development-guide/features/

It is required that all of our client libraries that use a 0.8.x version number, where possible, adhere to this specification ensuring feature compatibility across all languages and platforms. To ensure that we do not have regressions in future from this specification, all of the features within the 0.8 spec should have a matching test as well.

Please can you review this library against the feature set and do the following:

* Please copy & paste all the feature details in http://docs.ably.io/client-lib-development-guide/features/ into a Google Spreadsheet or something similar, and where possible, provide a link to a test this library that assures us that the intended functionality is implemented. Sometimes a test is not required, but please make us aware when this is not the case in the comments. See the [PHP Rest library example](https://docs.google.com/spreadsheets/d/1Imn8zgj4-ZmUT4hCRbjyb0a-N5Pr61QrWhcJAMvpIrs/edit#gid=0).  This is quite onerous, however it is far more difficult for us to validate this than the client library developer who knows the code. 
* Check that the README.md is up to date with the [Ruby version](https://github.com/ably/ably-ruby/blob/master/README.md) with details such as how to install it from a package manager if applicable.
* If any features from above are missing, please can you add a "Known Limitations" section to your README documenting the missing features from the client library.

**Comment by rjeczalik** [comment]
@mattheworiordan: The spec status for Go library is here: https://docs.google.com/spreadsheets/d/1gvN6y0KuzXsN6IOL4LGNbcIeZj-VKZ0U1dAhQrmPz7U/edit#gid=0.

**Comment by mattheworiordan** [comment]
Closing this as mostly addressed with the exception that there are known features not implemented
