### ISSUE TITLE
Indentation is missing in README examples

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-go#339]
It looks like some effort may have been made to remove tabs but we now have a flat structure. e.g.:

```go
if err != nil {
panic(err)
}
```

Where I would expect something like:

```go
if err != nil {
    panic(err)
}
```

With a call needing to be made on whether the indent level should be 2, 4 or 8 spaces. If 8 is the idiomatic default width for a tab in Go/Gofmt then we should perhaps go for that (even though that emotionally pains me 😆).

**Comment by lmars** [comment]
Should it not just be a tab? Like:

```go
if err != nil {
	panic(err)
}
```

**Comment by lmars** [comment]
Looks like the tabs were removed in https://github.com/ably/ably-go/commit/98b5fa2458890ee27c6e969efe41899a3844722d#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5, so we should just revert that change.
