### ISSUE TITLE
Update golang.org/x/net dependency (January 2019 > June 2021)

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-go#341]
We appear to be on `v0.0.0-20190110200230-915654e7eabc` suggesting a January 2019 build, however I can't see that version suffix listed in [the versions list for this package](https://pkg.go.dev/golang.org/x/net?tab=versions). Curious. 🤔 

Latest version, at the time of writing this, is `v0.0.0-20210614182718-04defd469f4e` (14 June 2021).

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1018) by [Unito](https://www.unito.io)
┆sprint: Backlog

**Comment by tcard** [comment]
`v0.0.0-20190110200230-915654e7eabc` is a [pseudo-version](https://golang.org/doc/modules/version-numbers#tmp_1). That version list probably contains only those pseudo-versions that are cached in the pkg.go.dev servers. Otherwise it would contain every commit in the repo.

**Comment by Rosalita** [comment]
Closing this issue as the project is no longer on `v0.0.0-20190110200230-915654e7eabc` 

This dependency is currently at `v0.0.0-20211015210444-4f30a5c0130f` as per above comment, this is a pseudo-version which signals that this module is still in development and could be unstable. Without a pressing reason to upgrade, we should leave this dependency alone for now.
