### ISSUE TITLE
Update github.com/ugorji/go/codec dependency (July 2019 > May 2021)

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-go#342]
We're requiring `v1.1.7` but the latest version is `v1.2.6`.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1019) by [Unito](https://www.unito.io)
┆sprint: SDK 2022-Q2-S3 28/04

**Comment by Rosalita** [comment]
This package now appears to be at https://github.com/ugorji/go and the latest version is `1.2.7` Looking back through release notes there's a number of performance improvements and no obvious reason not to upgrade. We should however do some regression testing to check that things still work as expected after updating this dependency.
