### ISSUE TITLE
Update github.com/stretchr/testify dependency (August 2019 > January 2021)

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-go#343]
We're requiring `v1.4.0` but the latest version is `v1.7.0`.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1021) by [Unito](https://www.unito.io)
┆sprint: SDK 2022-Q2-S4 12/05

**Comment by tcard** [comment]
Actually we should get rid of this dependency. It's only used in a couple places.

**Comment by sacOO7** [comment]
I am not sure about this one, it simplifies lot of our assertions though. But we had discussion to remove it, since it can create version conflicts for users who install this package with different version of testify

**Comment by tcard** [comment]
> I am not sure about this one, it simplifies lot of our assertions though

Maybe it would if we used them extensively, but we use them in [12 lines contained in 2 tests](https://github.com/ably/ably-go/blob/eb709f3c0983334da1107035de64669599b057d4/ably/error_test.go) (among a total of around 309 tests).

**Comment by Rosalita** [comment]
Internal conversation about `stretchr/testify/assert` back in February 2022 raised the following points:

We definitely want to be consistent in our approach to assertions. @lmars and @Rosalita both believe we should fully adopt `testify/assert`. 

There was a concern from @sacOO7 that adding testify/assert as a dependency would create version conflicts for downstream users, however it was noted that testify/assert already is already a dependency of this project. So if conflict was going to happen, it's already happened.

After reaching this decision #456 was completed to standardise test assertions in this project to use `testify/assert`

The version of `testify/assert` this project currently uses is 1.4..0. `testify/assert` accidentally released a breaking change in `1.6.0`, which was reverted in `1.6.1`. So given there are no breaking changes between `1.4.0` and `1.7.1` there should be nothing to stop this dependency being updated to `1.7.1` in this project.
