### ISSUE TITLE
Clean up ably/doc_test.go Example_paginatedResults()

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-go#345]
This looks like a work in progress, with a `TODO` baked into the call to `fmt.Println`.

```go
package ably_test

import "fmt"

func Example_paginatedResults() {
	fmt.Println("TODO once the Requests method is adapted")
	// Output: TODO once the Requests method is adapted
}
```

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1023) by [Unito](https://www.unito.io)
┆sprint: Backlog

**Comment by mohyour** [comment]
Done in #478
