### ISSUE TITLE
Lint code, probably using `gofmt`

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-go#346]
As explained to me by @lmars [elsewhere (internal)](https://ably-real-time.slack.com/archives/C0114KK7S6R/p1625735848027600?thread_ts=1623922381.097100&cid=C0114KK7S6R):

> `gofmt` by default just prints the changes it would make, the `-w` flag makes it rewrite the source files, and `-l` makes it print the filenames it would change

This should run as a core check in CI.

The majority of the work required on this issue will likely be fixing violations, for which the same tool can probably be used.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1026) by [Unito](https://www.unito.io)
┆sprint: SDK 2022-Q2-S4 12/05

**Comment by Rosalita** [comment]
Rather than having CI run commands that change code, I think the approach we need here is for CI to fail if the code is not formatted. By doing this, the developer can format it and commit/amend the change.

We need to check both the `ably` and `ably-test` folders for unformatted code. e.g. If the output to `gofmt -l ably` and `gofmt -l ably-test` is not nil, fail CI.

**Comment by QuintinWillison** [comment]
Agreed, we would _never_ want to engineer a scenario where CI _changes_ the source code.

What we could consider, however, if the `gofmt -l` exit code route doesn't work out, is running `gofmt` in CI and then using Git to check whether the working state is still clean.

**Comment by Rosalita** [comment]
1. using `gofmt -l ./...` and checking no files are listed.
2. using `go fmt ./...` and then checking `git status` to see if any files were changed

Either of these would do the trick, I'm not fussy go with whichever is easiest to read :)

**Comment by Rosalita** [comment]
Note that option 2 would change the file and option 1 would leave it alone.
