### ISSUE TITLE
Surface API reference docs

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-go#347]
We may be able to use [gopages](https://johnstarich.com/go/gopages/pkg/github.com/johnstarich/go/gopages/), as suggested by lmars [here (internal)](https://ably-real-time.slack.com/archives/C0114KK7S6R/p1623926815099500?thread_ts=1623922381.097100&cid=C0114KK7S6R).

To be uploaded to `sdk.ably.com` using our [Upload Action](https://github.com/ably/sdk-upload-action), modelled on similar workflows we have in other repositories (e.g. [ably-flutter](https://github.com/ably/ably-flutter/blob/main/.github/workflows/docs.yml) and [ably-asset-tracking-android](https://github.com/ably/ably-asset-tracking-android/blob/main/.github/workflows/docs.yml)).

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1027) by [Unito](https://www.unito.io)

**Comment by sacOO7** [comment]
Related to #559
