### ISSUE TITLE
Rename ClientOption type to something better describing its purpose

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-go#348]
Simply `ClientOption`, as it is currently, is too overloaded a term. It's defined in `ably/options.go` (new for 1.2.0 release).

I've suggested `ClientOptionApplicator` but others may have better ideas.

See [this thread (internal)](https://ably-real-time.slack.com/archives/C0114KK7S6R/p1625731484021700).

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1028) by [Unito](https://www.unito.io)
┆sprint: Backlog

**Comment by tcard** [comment]
This pattern is commonly called "functional options", it's very common in Go libraries and it's customary for naming to follow this pattern of having a function type with a "Option" suffix. I'd say ClientOption should be clearer than ClientOptionApplicator for a typical Go programmer.

**Comment by sacOO7** [comment]
Yeah, found out this is a standard pattern. Since it's a idiomatic convention, typical go programmer should be able to understand it.
https://www.sohamkamani.com/golang/options-pattern/

**Comment by lmars** [comment]
From a conceptual point of view, an Ably client is initialised with a set of client options, where each element in that set is an individual client option (e.g. a key, a client ID, an environment etc.).

As part of the 1.2 API design, we [discussed and agreed](https://github.com/ably/ably-go/issues/197#issuecomment-710844145) to use functional options, whereby the set of client options is a slice of individual client options passed to the client constructor, like:

```go
ably.NewRealtime(
	ably.WithKey("<key>"),
	ably.WithClientID("<clientID>"),
	ably.WithEnvironment("<environment>"),
)
```

Written differently, the user may want to construct the set of client options separately, in which case the code would look something like:

```go
clientOptions := []ably.ClientOption{
	ably.WithKey("<key>"),
	ably.WithClientID("<clientID>"),
}
if xxx {
	clientOptions = append(clientOptions, ably.WithEnvironment("<environment>"))
}
ably.NewRealtime(clientOptions...)
```

In both these cases, I think each element of the set of client options having type `ClientOption` makes sense, the fact that internally `ClientOption` is a function that gets called by the constructor is an implementation detail that I don't believe needs to be made apparent in the name of the type.

**Comment by Rosalita** [comment]
Hi @QuintinWillison after reading this issue and comments. I don't feel we need to rename the `ClientOption`. After reading @lmars comment, do you also feel the naming can remain unchanged? Maybe we can we resolve this issue by adding a little documentation in the project readme around the functional option pattern the project uses.

**Comment by QuintinWillison** [comment]
Agreed, let's leave the name unchanged. I'm not a Golang-native, so definitely happy to go with consensus from those who know the language much better than I. 👍
