### ISSUE TITLE
Document ably/generate.go

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-go#351]
This file in its current state is somewhat opaque, with commented out lines and no explanatory commentary.

Perhaps document as commentary in place within this file if that's appropriate, but may also need referencing from the contributing guide.

See [this thread (internal)](https://ably-real-time.slack.com/archives/C0114KK7S6R/p1625732470023400), in which @sacOO7 responded to me with:

> This one is responsible for generating go files from mentioned README code snippets
> We run these go files as a part of test suite to make sure, snippets mentioned in README work as expected
> The commented code are actually cmd instructions to generate the files

He also referred me to [this article on `go generate`](https://ehrt74.medium.com/go-generate-89b20a27f7f9).

See also https://github.com/ably/ably-go/pull/206.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1031) by [Unito](https://www.unito.io)
┆sprint: SDK 2022-Q2-S5 26/05

**Comment by tcard** [comment]
> This file in its current state is somewhat opaque, with commented out lines and no explanatory commentary.

Those aren't commented out lines, they are directives for `go generate` (which happen to be comments for Go-as-a-language). If you know how `go generate` works, then `generate.go` should be very self-explanatory.
