### ISSUE TITLE
Document ably/export_test.go

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-go#352]
On inspection the contents of this file and its purpose were complete opaque to me.

See [this thread (internal)](https://ably-real-time.slack.com/archives/C0114KK7S6R/p1625732323022900), where @sacOO7 explained:

> This exports types that we can be used in writing unit/integration tests without exposing them into public code

And when I asked if this is documented somewhere in this repository he added:

> No, I don't think this is mentioned anywhere. As file name says, `export_test`, means types exported for using them in tests. Still, we need to find usages of these exported types to come to that conclusion, so basically need to put some time reading the code

Hence the creation of this issue under which to do that work, with the outcome being that we perhaps include some explanatory commentary in this file and maybe also something in the contributing guide.

**Comment by Rosalita** [comment]
Hi @QuintinWillison Back in February, I added some documentation around how tests work in this project. See https://github.com/ably/ably-go/commit/7ff1439460c7d310155f56c3c8c56e81e5e66561

I am hopeful this explanation is sufficient. I feel we should be able to close this issue now documentation has been added.

**Comment by QuintinWillison** [comment]
Thanks. That's really helpful. Let's close this. 😁
