### ISSUE TITLE
Migrate from deprecated websocket package

### ISSUE THREAD

**Issue by Jmgr** [ably/ably-go#368]
Ably-go is currently using golang.org/x/net/websocket as its websocket package. Seeing that this package is now deprecated (see https://github.com/golang/go/issues/18152 and https://pkg.go.dev/golang.org/x/net/websocket) we might want to migrate to another one.

A good alternative could be https://github.com/nhooyr/websocket, as it provides more features (notably the ability to use the browser's WebSockets transparently when targetting wasm, allowing you to write a Go app for the browser that can connect to Ably). Both APIs are not compatible though, so this will require a few code changes.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1115) by [Unito](https://www.unito.io)
┆sprint: Backlog

**Comment by Rosalita** [comment]
Hi @Jmgr I would like to try get this issue back on track. 

I can see in the docs for deprecated package that they recommend two packages
`https://godoc.org/github.com/gorilla/websocket`
`https://godoc.org/nhooyr.io/websocket`

I can also see that you have a draft PR open here https://github.com/ably/ably-go/pull/433 that implements one of those alternatives. 

Would it be possible to get your draft PR rebased against latest main branch and ready for review?

**Comment by Rosalita** [comment]
I've taken a look at the failing test and commented on the PR.

**Comment by Rosalita** [comment]
Due to issues with existing tests, we need to complete https://github.com/ably/ably-go/issues/541 before we can switch the websocket package.
