### ISSUE TITLE
How to issue a TokenRequest 

### ISSUE THREAD

**Issue by scohen-examity** [ably/ably-go#380]
I have this routine to create a TokenRequest:

func CreateAblyTokenRequest(channelName string) (*ably.TokenRequest, error) {
	var (
		exp time.Duration = defaultTTL
		err error
	)

	// get back configuration info
	clientopts, params := paramsAndOptions(channelName, exp)

	// create the ably rest client
	pubsubClient, err := ably.NewREST(clientopts...)
	if err != nil {
		return nil, err
	}

	// create a token request to return to the requestor 
	tok, err := pubsubClient.Auth.CreateTokenRequest(params)
	if err != nil {
		return nil, err
	}

	return tok, nil
}

// capability allows for creating an ably capabilities map for setting up access permissions
type capability map[string][]string

// paramsAndOptions creates the ably configuration data blocks needed to create a token request
func paramsAndOptions(channel string, ttl time.Duration) ([]ably.ClientOption, *ably.TokenParams) {
	cap := make(capability)
	cap[channel] = []string{"publish", "subscribe"}
	b, _ := json.Marshal(cap)

	params := &ably.TokenParams{
		TTL:        ttl.Microseconds(),
		Capability: string(b),
		ClientID:   channel,
	}

	clientopts := []ably.ClientOption{
		ably.WithQueryTime(true),
		ably.WithClientID(channel), // this is important so each 'connection' is associated with the ClientID
		ably.WithKey(pubsubKey),
	}

	return clientopts, params
}

I get back this:

token:
{
  "capability": "{\"MyTestChannel\":[\"publish\",\"subscribe\"]}",
  "clientId": "MyTestChannel",
  "keyName": "0-xxxX.xxxXXX",
  "mac": "QksYqScrODhUtx/x0OdXZ3nLj62aXaltlhDcg7UgJE0=",
  "nonce": "b73ebacc3ebd83f584d470bfe1554bd0",
  "timestamp": 1630084148000,
  "ttl": 18000000000
 }

---

Given the generated json struct, I tried to verify doing this:

b, _ := json.Marshal(token)
client, err := ably.NewRealtime(ably.WithToken(string(b)))
	if err != nil {
		panic(err)
	}

No error is return, but if I try to use the client to Publish a message, I get:
[ERROR] failure sending message (serial=0): [ErrorInfo :Invalid accessToken in request

Is there an example of generating a TokenRequest (to given to a client) and how to use it?

**Comment by lmars** [comment]
@scohen-examity I'm going to assume my answer was sufficient and close this issue, do let us know if you need further assistance.
