### ISSUE TITLE
Unimplemented Test: Test_RTN4a_ConnectionEventForStateChange ably.ConnectionStateSuspended

### ISSUE THREAD

**Issue by tomkirbygreen** [ably/ably-go#401]
┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1292) by [Unito](https://www.unito.io)

**Comment by Rosalita** [comment]
Note: this test is not skipped because it is failing. Part of this test is skipped with a note that `SUSPENDED not yet implemented`.

**Comment by QuintinWillison** [comment]
Work on this should take place under #568.
