### ISSUE TITLE
Unimplemented Test: TestRealtimeConn_RTC8a_ExplicitAuthorizeWhileConnected

### ISSUE THREAD

**Issue by tomkirbygreen** [ably/ably-go#408]
┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1293) by [Unito](https://www.unito.io)

**Comment by Rosalita** [comment]
Note: This test is not skipped because it is failing, it is skipped because `"RTC8a4: reauthorize with JWT token"` functionality has not been implemented yet.

**Comment by QuintinWillison** [comment]
Work on this should take place under #569.
