### ISSUE TITLE
Investigate re-enabling flaky tests.

### ISSUE THREAD

**Issue by Rosalita** [ably/ably-go#438]
The following tests have been identified as flakey.

```
Test_RTN4a_ConnectionEventForStateChange
TestAuth_BasicAuth
TestAuth_ClientID
```

Recently a PR was raised to this code base, out of 4 test runs for that PR the following was observed.

Attempt #1 all tests failed to start - this run was ignored.

Attempt #2 the follow test failed on Go 1.16

```
=== RUN   Test_RTN4a_ConnectionEventForStateChange
=== RUN   Test_RTN4a_ConnectionEventForStateChange/on_CONNECTING
    ably_test.go:66: safeclose 1: failed to close *ablytest.Sandbox: Delete "https://sandbox-rest.ably.io/apps/_tmp_aRmoog": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
=== RUN   Test_RTN4a_ConnectionEventForStateChange/on_CONNECTED
    realtime_conn_spec_test.go:148: timed out waiting for channel receive
    ably_test.go:66: safeclose 0: failed to close ablytest.realtimeIOCloser: context deadline exceeded
=== RUN   Test_RTN4a_ConnectionEventForStateChange/on_DISCONNECTED
--- FAIL: Test_RTN4a_ConnectionEventForStateChange (182.20s)
    --- PASS: Test_RTN4a_ConnectionEventForStateChange/on_CONNECTING (61.86s)
    --- FAIL: Test_RTN4a_ConnectionEventForStateChange/on_CONNECTED (68.89s)
    --- FAIL: Test_RTN4a_ConnectionEventForStateChange/on_DISCONNECTED (51.44s)
panic: request error: Service Unavailable ("{\"message\":\"Ably's routing layer was unable to service this request\",\"code\":50305,\"statusCode\":503,\"href\":\"https://help.ably.io/error/50000\"}") [recovered]
	panic: request error: Service Unavailable ("{\"message\":\"Ably's routing layer was unable to service this request\",\"code\":50305,\"statusCode\":503,\"href\":\"https://help.ably.io/error/50000\"}")
```

And the following test failed on Go 1.17

```
=== RUN   TestAuth_BasicAuth
--- FAIL: TestAuth_BasicAuth (0.53s)
panic: request error: Service Unavailable ("{\"message\":\"Ably's routing layer was unable to service this request\",\"code\":50305,\"statusCode\":503,\"href\":\"https://help.ably.io/error/50000\"}") [recovered]
	panic: request error: Service Unavailable ("{\"message\":\"Ably's routing layer was unable to service this request\",\"code\":50305,\"statusCode\":503,\"href\":\"https://help.ably.io/error/50000\"}")
```

Attempt #3 The following tests failed on Go 1.16

```
=== RUN   TestAuth_ClientID
    auth_test.go:673: Close()=waiting on Result timed out after 30s
--- FAIL: TestAuth_ClientID (37.98s)
```

Attempt #4 all tests passed.

These tests are failing due to timeout and a service which was unavailable.

These tests have been set to skip as in their current state they are not adding value to the project. This ticket is to investigate re-enabling them.

┆sprint: Backlog

**Comment by lmars** [comment]
Just to give some opinions on these test failures:

> failed to close *ablytest.Sandbox: Delete "https://sandbox-rest.ably.io/apps/_tmp_aRmoog": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

Apps created in sandbox are temporary and get cleaned up automatically after a while, so if explicitly deleting them is a flaky operation that often times out, perhaps we should just not explicitly delete them in SDK tests?

Doing this will also save us some time in the tests not waiting for that to complete, since I just tried and it took 5s:

```
$ time curl -X DELETE -u "_tmp_oCUSGA.0WhQQQ:******" "https://sandbox-rest.ably.io/apps/_tmp_oCUSGA"

real    0m5.072s
user    0m0.017s
sys     0m0.017s

```

@SimonWoolf WDYT? Could not explicitly deleting them cause any issues?

> panic: request error: Service Unavailable ("{\"message\":\"Ably's routing layer was unable to service this request\",\"code\":50305,\"statusCode\":503,\"href\":\"https://help.ably.io/error/50000\"}") [recovered]

The sandbox cluster experienced some issues between 7pm and 8pm UTC yesterday (27th Jan), so if these tests failed around that time, that would explain these failures, and so the tests can probably be re-enabled now that sandbox is functional.

**Comment by Rosalita** [comment]
Closing issue as resolved by https://github.com/ably/ably-go/pull/493
