### ISSUE TITLE
Add ConnectionKey to message

### ISSUE THREAD

**Issue by jamienewcomb** [ably/ably-go#442]
If you are publishing from a REST client and want to prevent one particular realtime client (which has echoMessages set to false) from receiving the message, as if that client was the one that published the message, you can do that by setting the connectionKey.

┆sprint: SDK 2022-Q1-S3

**Comment by jamienewcomb** [comment]
@Rosalita is testing if this has been fixed by https://github.com/ably/ably-go/pull/437

**Comment by sacOO7** [comment]
Need to add test for the same as per https://faqs.ably.com/is-it-possible-to-prevent-messages-published-being-echoed-back-to-the-publishing-client

**Comment by sacOO7** [comment]
We have a `ProtocolMsg` that wraps actual `Data`. ProtocolMsg generally carries the context of the message. I think the fix might be related to https://github.com/ably/ably-go/pull/378. Though, the internal empty connectionkey field is updated from outside.

**Comment by Rosalita** [comment]
As the fix failed, I've raised https://github.com/ably/ably-go/pull/443 to fix the fix.
