### ISSUE TITLE
Test improvements - Move integration tests to their own package.

### ISSUE THREAD

**Issue by Rosalita** [ably/ably-go#458]
Related to #447 

Now we have clear separation between unit tests and integration tests. We should consider moving the integration tests to their own package.

We could make a package called `integration_test` and move the the integration tests there. 

If we used a `TestMain` function inside that package, we could add test set up and teardown there. Test setup could set the environment variables that the integration tests require. This would allow us to delete the bash script that is currently used to run the test.

An example of using TestMain: 

```
func TestMain(m *testing.M) {

	flag.Parse()
	// Test setup

	// Run tests
	exitCode := m.Run()

	// Test teardown
	os.Exit(exitCode)
}
```

The advantages of moving integration tests to their own package:

* There would be fewer test files in the root of the project making it easier to work with tests.
* It would also improve developer experience as they could be run using the Go tool chain ( `go test ./integration_test` instead of having to run via a bash script)
* We would no longer need to use build tags at the top of each test file to separate unit tests and integration tests.

Acceptance criteria:

* Integration tests are moved to a new package.
* Integration tests can be run in CI without the need for a bash script. *(stretch goal)*
* Build tags are removed from test files.
* CI pipeline steps are updated so they no longer rely on build tags.
* Project readme file is updated to explain how to run all tests.

┆sprint: SDK 2022-Q1-S4

**Comment by Rosalita** [comment]
Moving the integration tests to their own package is currently impossible due to the way files are exported in this project. 

There is a file called `export_test.go` which is in the main package (`package ably`) this file takes private functions and variables and makes them publicly available to only the package `ably_test`. Moving the tests to their own package, they would live outside `ably_test` and therefore not have the private files they need available to run.

We currently have the following options:
1. Leave the integration tests where they are in the main package, separated by build tags in files suffixed `_integration_test`.
2. Find out why the private functions and variables which the integration tests are dependent on are private. Then consider the risk/benefit of making them public so they can be used by a different package. If it is possible to make them public, then it would be possible to move the integration tests to their own package.

**Comment by lmars** [comment]
> Then consider the risk/benefit of making them public so they can be used by a different package

We could make them public but within an internal package, see https://dave.cheney.net/2019/10/06/use-internal-packages-to-reduce-your-public-api-surface.

**Comment by Rosalita** [comment]
I read the article above about using internal packages to reduce public API surface. Using this solution would involve moving a significant amount of core ably-go code down into internal packages.

For example, at the moment `export_test.go` contains
```
func (c *REST) Post(ctx context.Context, path string, in, out interface{}) (*http.Response, error) {
	return c.post(ctx, path, in, out)
}
```
This exposes the post method in `rest_client.go` which means to share this code with a new test package, we would need to move all the code in `rest_client.go` to a new internal package like `internal/rest_client`.

Given that the `export_test.go` file makes code in 19 different files `options.go`, `rest_client.go`, `auth.go`, `error.go`, `realtime_channel.go`, `event_emitter.go`, `realtime_conn.go`, `state.go`, `logger.go`, `proto_action.go`, `proto_channel_options.go`, `proto_protocol_message.go`, `proto_types.go`, `proto_error.go`, `proto_crypto.go`, `proto_http.go`, `proto_action.go`, `os_version_unix.go`, `websocket.go` publicly available to package `ably_test` this feels like an awful lot of code to move to internal packages, just so that it could be shared with a new test package.

This approach probably is not the best solution for this project.
