### ISSUE TITLE
Passing tests appear to have failed in Travis

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-go#47]
See build https://travis-ci.org/ably/ably-go/jobs/91915893

At the end, Travis states that it failed, whereas it looks like the tests have passed.

@rjeczalik can you fix that please?

**Comment by rjeczalik** [comment]
Sure, there's one flaky test afaik - `TestAuth_RequestToken_PublishClientID`.

**Comment by tcard** [comment]
Closing due to old age.
