### ISSUE TITLE
Support Go 1.18

### ISSUE THREAD

**Issue by Rosalita** [ably/ably-go#474]
Go 1.18 was officially released yesterday 🎉 

The project readme says
```
## Supported Versions of Go

Whenever a new version of Go is released, Ably adds support for that version. The [Go Release Policy](https://golang.org/doc/devel/release#policy) supports the last two major versions. This SDK follows the same policy of supporting the last two major versions of Go.

```

To support 1.18, we should take the following actions:
- Increase the minimum version of Go required to use the SDK by bumping the version of Go in the go.mod file from 1.16 to 1.17 
- Add Go version 1.18 to the GitHub Workflow so all tests run against Go 1.18
- Remove Go version 1.16 from the GitHub Workflow so tests no longer run against Go 1.16

┆sprint: SDK 2022-Q1-S6

**Comment by Rosalita** [comment]
It's also worth noting that once we no longer support Go version 1.16, we can also remove old style build tags from the project as the new style build tags came in 1.17.

**Comment by Morganamilo** [comment]
Even if we don't support it there's no reason to make it not work. Also I believe go will complain at you for not having both as they want stuff to work on old versions.
