### ISSUE TITLE
Paginated Result .Item() return pointer that is then changed

### ISSUE THREAD

**Issue by Morganamilo** [ably/ably-go#496]
Calling .Item() returns a pointer that references the item variable in the Paginated Result structs. When .Next() is called it changes the current item and thus changes the value of the pointer that was already given out.

The pointer given by .Item() should create a new pointer instead.

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-1799) by [Unito](https://www.unito.io)
┆sprint: SDK 2022-Q2-S7  23/06

**Comment by Rosalita** [comment]
For the REST client, there are three different structs for pagination which have `Next()` and `.Item()` methods, `StatsPaginatedItems`, `MessagesPaginatedItems`, `PresencePaginatedItems` we need keep in mind when fixing this, it will most likely need to be fixed in three separate places for each of these types.

**Comment by Morganamilo** [comment]
So I'm not sure where the bug actually is but I think it's in the ably test package.

The pagination code is so complex and there's so many different types it's very hard to read. On top of that the ably test package wraps all of these using one implementation that reflects the pagination function names.

In essence the ablytest wrapper has a .Item() function that hands out the current item. While .Next() moves on to the next item. Issue is that the item handed out seems to actually be a pointer to some value inside the pagination object. Meaning when .Next() is called it actually switches out all existing objects generated via .Item().

This was partially fixed using a hack where we just deref the value and take a new reference to it to force a different address. https://github.com/ably/ably-go/blob/ec4750d04b5de551c9d06674f263f800e405fcb0/ablytest/pagination.go#L125

**Comment by mohyour** [comment]
Based on the current implementation of pagination, the hack added for the test seem to be a fix we can hang on to.
