### ISSUE TITLE
Sometimes integration tests fail with a websocket dial error.

### ISSUE THREAD

**Issue by Rosalita** [ably/ably-go#512]
One example of this was seen on this run https://github.com/ably/ably-go/runs/6405356210?check_suite_focus=true

```
=== RUN   TestRealtimePresence_Sync250
    realtime_presence_integration_test.go:71: 
        	Error Trace:	realtime_presence_integration_test.go:71
        	Error:      	Received unexpected error:
        	            	[ErrorInfo :websocket.Dial wss://sandbox-realtime.ably.io:443?echo=true&format=msgpack&heartbeats=true&key=_tmp_DELqOQ.4bzRew%3AZnRMoEAyCUwMR0BHKwYz3y7HUeuzkGl4FgEYMuHbmno&timestamp=1652358451326&v=1.2: read tcp 10.1.1.102:52358->52.85.35.170:443: read: connection reset by peer code=80003 disconnected statusCode=0] See https://help.ably.io/error/80003
        	Test:       	TestRealtimePresence_Sync250
```

Note the error message "read: connection reset by peer". This feels like the sandbox server is closing the connection and the test then has an error because it has been disconnected.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1865) by [Unito](https://www.unito.io)
┆sprint: SDK 2022-Q2-S5 26/05

**Comment by Rosalita** [comment]
Reopening as this issue appeared in this test run.

https://github.com/ably/ably-go/runs/6754401388?check_suite_focus=true

It hasn't been resolved by running the tests as separate suites.

**Comment by Rosalita** [comment]
I've been lucky enough to see this error happen while I had log level set to debug. Attaching the debug log for analysis and investigation
[debug-log.txt](https://github.com/ably/ably-go/files/8859796/debug-log.txt)

**Comment by cruickshankpg** [comment]
I would expect to see connection reset by peer errors when instances in our routing layer are redeployed as these will close their TCP connections. Redeploys of the instances are relatively common and when testing against real endpoints the test and definitely ably-go should handle these errors.

**Comment by cruickshankpg** [comment]
To reproduce I would connect via a local TCP proxy that drops connections

**Comment by Rosalita** [comment]
Closing at the request of @deanna-lad
