### ISSUE TITLE
Testing challenges around use of embedded sync.Mutex in types

### ISSUE THREAD

**Issue by Rosalita** [ably/ably-go#535]
Some of the the types used in this project have `sync.Mutex` embedded directly into them e.g `RealtimeChannel` https://github.com/ably/ably-go/blob/main/ably/realtime_channel.go#L169 and `RealtimePresence` https://github.com/ably/ably-go/blob/main/ably/realtime_presence.go#L22

the [sync package](https://go.dev/src/sync/mutex.go) states `Values containing the types defined in this package should not be copied.` This creates a challenge when we want to copy a mocked type that contains a `sync.Mutex` into a unit tests. We simply can't do this as `go vet` (correctly) objects to copying the mutex. We also have no way to test whether any particular `sync.Mutex` is locked or unlocked as a result of code execution because we can't use dependency injection to inject a mock mutex into the code.

It might be worth investigating if representing `sync.Mutex` with the `sync.Locker` interface would make some of the code in this project testable at the unit test level. Interfaces are essentially mocking points and using `sync.Locker` could allow us to use a mock lock to make assertions in unit tests.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1941) by [Unito](https://www.unito.io)
┆sprint: Backlog

**Comment by lmars** [comment]
> This creates a challenge when we want to copy a mocked type that contains a `sync.Mutex` into a unit tests

Can you give an example of such a test? I'm not sure I fully understand the challenges involved.

**Comment by Rosalita** [comment]
> > This creates a challenge when we want to copy a mocked type that contains a `sync.Mutex` into a unit tests
> 
> Can you give an example of such a test? I'm not sure I fully understand the challenges involved.

Sure, I have an open PR at the moment where I was forced to define mocks for a realtime channel test inside the test execution see https://github.com/ably/ably-go/pull/534/files

**Comment by lmars** [comment]
> I was forced to define mocks for a realtime channel test inside the test execution

Ok thanks, and so if there was no mutex involved and `RealtimeChannel` could be freely copied, how would the test change? I think I'm not understanding how being able to copy `RealtimeChannel` relates to improving that test.

**Comment by Rosalita** [comment]
> > I was forced to define mocks for a realtime channel test inside the test execution
> 
> Ok thanks, and so if there was no mutex involved and `RealtimeChannel` could be freely copied, how would the test change? I think I'm not understanding how being able to copy `RealtimeChannel` relates to improving that test.

So if RealtimeChannel could be freely copied the mock could be defined in the table test e.g the map[string]struct which would allow a different mock to be set up for each test.  This would get rid of a hacky if else statement to switch the mock in the test depending on the name of the channel in the test.  Taking it a step further if the type could be copied, the mocks could be generated by a function in mocks_test.go.

**Comment by lmars** [comment]
Sorry, I'm still not quite following, where exactly in the code would the copy happen? If you could demonstrate what the test code would look like with the copying, it might make it clearer.

**Comment by Rosalita** [comment]
I'm hoping I can explain what I mean with a code example. This code below uses an established  'table test' pattern to initialise a different mock for each test (which is run as a sub-test). 

```
func TestChannelGet(t *testing.T) {
	tests := map[string]struct {
		mock                 RealtimeChannels
		name                 string
		expectedChannelName  string
		expectedChannelState ChannelState
	}{
		"If channel does not exist, it is created and initialised": {
			mock: RealtimeChannels{
				chans: map[string]*RealtimeChannel{},
				client: &Realtime{
					rest: &REST{
						log: logger{l: &stdLogger{mocklogger}},
					},
				},
			},
			name:                 "new",
			expectedChannelName:  "new",
			expectedChannelState: ChannelStateInitialized,
		},
	}

	for testName, test := range tests {
		t.Run(testName, func(t *testing.T) {
			result := test.mock.Get(test.name)
			assert.Equal(t, test.expectedChannelName, result.Name)
			assert.Equal(t, test.expectedChannelState, result.state)
		})
	}
}

```

If the mocked type contains a sync.Mutex, the above code will give this `go vet` error 

"var test copies lock: struct{mock github.com/ably/ably-go/ably.RealtimeChannels; name string; expectedChannelName string; expectedChannelState github.com/ably/ably-go/ably.ChannelState} contains github.com/ably/ably-go/ably.RealtimeChannels contains sync.Mutex"

This forces any mocked values to exist in the body of the test, they can't be defined in the table as they would be copied by value in the loop that executes the sub-tests. The example code below is the work around.

```

func TestChannelGet(t *testing.T) {
	tests := map[string]struct {
		name                 string
		expectedChannelName  string
		expectedChannelState ChannelState
	}{
		"If channel does not exist, it is created and initialised": {
			name:                 "new",
			expectedChannelName:  "new",
			expectedChannelState: ChannelStateInitialized,
		},
	}

	for testName, test := range tests {
		t.Run(testName, func(t *testing.T) {

			mockedRealtimeChannels := RealtimeChannels{
				chans: map[string]*RealtimeChannel{},
				client: &Realtime{
					rest: &REST{
						log: logger{l: &stdLogger{mocklogger}},
					},
				},
			}

			result := mockedRealtimeChannels.Get(test.name)
			assert.Equal(t, test.expectedChannelName, result.Name)
			assert.Equal(t, test.expectedChannelState, result.state)
		})
	}
}
```

If mocked values in different states were required for each test, this would quickly become unreadable as there would not be a clear relationship expressed between each mock and each test.

**Comment by Rosalita** [comment]
Pointers works. I've raised https://github.com/ably/ably-go/pull/542 to make the change, many thanks 🙏
