### ISSUE TITLE
JWT (JSON Web Token) authentication

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-go#569]
Lack of support for JWTs is documented under [Known Limitations](https://github.com/ably/ably-go#known-limitations). It's also [highlighted in the tests](https://github.com/ably/ably-go/blob/25877a6c5cbb4182a4e8a12e8c8adeaf7a387e49/ably/realtime_conn_spec_integration_test.go).

Also, the concept of "unimplemented test" was introduced at some point to the backlog. I'm going to close all of these issues as they add no value to the backlog (the work to be done is under this issue) however I am recording them here for reference:

* https://github.com/ably/ably-go/issues/408
* https://github.com/ably/ably-go/issues/409

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4550) by [Unito](https://www.unito.io)

**Comment by SimonWoolf** [comment]
It looks like the only missing feature here is that the SDK doesn't handle a content-type of `application/jwt` as a synonym for `text/plain`. (After all, the SDK handles text tokens opaquely anyway; it doesn't need to anything special for JWT, it passes it on to the server same as with a legacy token string).

This is hardly essential; until that's implemented the customer can just have their auth server return encoded jwts with a content-type of `text/plain`.

I think listing "JWT authentication using auth-url is not implemented" as a "known limitation" is misleading; customers might be put off using a feature that basically works. We should just document the content-type limitation. (Or add support for the extra content-type, surely it's like one line of code)

**Comment by lmars** [comment]
> Or add support for the extra content-type, surely it's like one line of code

Definitely advocate for that...

https://github.com/ably/ably-go/blob/673864c17cce627bc09a283b953bd345458e52ca/ably/auth.go#L463

**Comment by sacOO7** [comment]
Link to internal conversation -> https://ably-real-time.slack.com/archives/CURL4U2FP/p1725031482412929

**Comment by sacOO7** [comment]
This issue is strongly related to [server/client initiated auth](https://github.com/ably/ably-go/issues/228).

**Comment by sacOO7** [comment]
Link to internal conversation -> https://ably-real-time.slack.com/archives/CURL4U2FP/p1713355380562679
