### ISSUE TITLE
Google App Engine

### ISSUE THREAD

**Issue by victoraugustolls** [ably/ably-go#57]
Is there a way to use it inside Google Apple Engine standard environment? If not, I think it would be an interesting addition, any thoughts?

**Comment by tcard** [comment]
@victoraugustolls We haven't done anything special to support it. It works on top of the standard net/http, and golang.org/x/net/websocket, so if Goole App Engine supports that, then it shouldn't be a problem.

**Comment by Rosalita** [comment]
Closing as this question was answered in 2017 an no further comments have been posted since then.
