### ISSUE TITLE
ID and Client ID is blank on realtime incoming messages.

### ISSUE THREAD

**Issue by corlinp** [ably/ably-go#58]
Found a possible bug that is causing trouble for me. Incoming realtime messages have a blank message ID and some other blank fields like Client ID. Historical messages DO have an ID. Other SDKs such as the Javascript library do report IDs in realtime.

Here is some test code that you can run, you should see that the message IDs are blank.

```
func main() {
	options := ably.NewClientOptions("APIKEY")
	var err error
	ablyClient, err := ably.NewRealtimeClient(options)
	ablyChannel := ablyClient.Channels.Get("test")

	go func() {
		number := 1
		for {
			time.Sleep(time.Second * 2)
			ablyChannel.Publish("test", fmt.Sprintf("Message number %v", number))
			number++
		}
	}()

	sub, err := ablyChannel.Subscribe("test")
	if err != nil {
		panic(err)
	}
	for msg := range sub.MessageChannel() {
		fmt.Printf("recv:\n\tName: %s\n\tData: %s\n\tID: %s \n\tClient ID: %s\n", msg.Name, msg.Data, msg.ID, msg.ClientID)
	}
}
```

┆sprint: SDK 2022-Q1-S8

**Comment by funkyboy** [comment]
Hi @tornato7 
Thanks for reporting this. I have been able to reproduce this. Will investigate further.
