### ISSUE TITLE
Panic in ablytest

### ISSUE THREAD

**Issue by agiacomolli** [ably/ably-go#601]
Hey all

We're trying to use the `ablytest` package to test our business logic, but we are running into a panic in `Sandbox.Options()` function due to `ClientOptionsInspector` being `nil`.

Any insights or suggestions on how to handle this? We're using version `1.2.12`.

Here's a MRE:

```go
package test

import (
	"testing"

	"github.com/ably/ably-go/ablytest"
)

func Test(t *testing.T) {
	app, err := ablytest.NewSandbox(nil)
	if err != nil {
		t.Fatal(err)
	}
	defer app.Close()

	opts := app.Options()
	t.Logf("app options: %v", opts)
}
```

And the output:

```
$ go test -v -count=1 ./test
=== RUN   Test
--- FAIL: Test (7.43s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1325c0d]

goroutine 34 [running]:
testing.tRunner.func1.2({0x1366540, 0x16601c0})
        /usr/local/Cellar/go@1.19/1.19.6/libexec/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
        /usr/local/Cellar/go@1.19/1.19.6/libexec/src/testing/testing.go:1399 +0x39f
panic({0x1366540, 0x16601c0})
        /usr/local/Cellar/go@1.19/1.19.6/libexec/src/runtime/panic.go:884 +0x212
github.com/ably/ably-go/ablytest.(*Sandbox).Options(0xc00018e0c0, {0x0, 0x0, 0x0})
        /Users/test/go/pkg/mod/github.com/ably/ably-go@v1.2.12/ablytest/sandbox.go:242 +0x3cd
github.com/test/test/test.Test(0xc0001b2340)
        /Users/test/client_test.go:16 +0xb5
testing.tRunner(0xc0001b2340, 0x13f5290)
        /usr/local/Cellar/go@1.19/1.19.6/libexec/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
        /usr/local/Cellar/go@1.19/1.19.6/libexec/src/testing/testing.go:1493 +0x35f
FAIL    github.com/test/test       7.710s
FAIL
```

**Comment by sacOO7** [comment]
Which version of `ably-go` are you using?

**Comment by agiacomolli** [comment]
Hi, `1.2.12`.

**Comment by sacOO7** [comment]
Hi @agiacomolli I will check and get back to you on this. I will post here if more information is needed.

**Comment by agiacomolli** [comment]
Hi @sacOO7, we found a solution. It works by setting these globals direct in the test file.

```go
func init() {
	ablytest.ClientOptionsInspector.UseBinaryProtocol = func(o []ably.ClientOption) bool {
		return false
	}
	ablytest.ClientOptionsInspector.HTTPClient = func(o []ably.ClientOption) *http.Client {
		return http.DefaultClient
	}
}
```

**Comment by sacOO7** [comment]
Great, I was able to reproduce the issue, when I ran it in a separate test file!
Though, I would not recommend using a sandbox for your own testing, since it's specifically intended for client library SDKs.
It can lead to flaky nature of tests, considering some beta features can be deployed on the sandbox environment so that they can be tested before going into production.

You can rather use, `ablyRealtimeClient` by passing the `ABLY_KEY`, which would be using a more stable ably prod environment.

```
client, err := ably.NewRealtime(ably.WithKey("xxx:xxx"))
```

**Comment by owenpearson** [comment]
hey @agiacomolli, just to reiterate @sacOO7's point here: the sandbox environment is hosted specifically for the purpose of running our own automated tests so we don’t provide any guarantees for support or that it will remain publicly accessible. Additionally, the sandbox environment is where we test new changes to our realtime APIs so you may encounter some unexpected changes in behaviour when using it. You’re welcome to continue using it for the time being, but we would advise you to consider running your tests against a production Ably app. It should be relatively straightforward to set up something equivalent to the ablytest.NewSandbox method using the [control api](https://ably.com/docs/control-api) (see also https://github.com/ably/ably-control-go).
