### ISSUE TITLE
Allow configuring ably/websocket read limits

### ISSUE THREAD

**Issue by codegoalie** [ably/ably-go#610]
The messages we are receiving through the Ably real-time client are somewhat large (seem to max out ~175k), but the default real limit for messages in `nhooyr.io/websocket` is 32,678 bytes. If a message is received larger than this limit, the connection is closed.

Ideally, we'd be able to set this message limit in the `ClientOptions`, but this seems like an implementation-specific configuration and may not apply to other connection mechanisms. 

I also see that the `Dial` is a client option. I'd like to use all of the `ably.websocketConn` (but increase the read limit) without needing to implement my own websocket connection/client functionality.

I'm happy to do some work here too and open a PR, but I want to make sure that 1) this is a change that would be welcome in the package and 2) the option I implement is the right path.

Thanks so much!!

-- Chris

**Comment by owenpearson** [comment]
Hey @codegoalie, thanks for reaching out!

The Ably service itself has a default limit of 64kb for PAYG accounts (see our [FAQ article](https://faqs.ably.com/what-is-the-maximum-message-size). If you have a hard requirement for larger messages, we can raise this to up to 256kb on a per-account basis but you would need to reach out to [support](https://ably.com/contact) to discuss. Alternatively, it might be worth considering if there's a way you can split up payloads yourself to avoid exceeding this limit.

I actually wasn't aware of the `nhooyr.io/websocket` limit, thank you for making us aware of this. We can increase this in a new version of the library, but if you need to send payloads of 175kb, for the above reasons, you will also need to increase the limits on your account. We're always happy to take PRs but it should be a trivial change so we should be able to do it quickly anyway :)

I hope this helps, let us know if you have any further questions

**Comment by codegoalie** [comment]
Hi! 

OK! I wasn't aware of the Ably limit. There may be some compression happening, because the messages are coming through when I used a local, modified version of `ably-go` which ups the limit. I just added `c.SetReadLimit(200000)` in `dialWebsocketTimeout` for testing.

Unfortunately, I'm only on the consumer side, so I don't have control over the message format/size.

If you think it's an easy change, I'm happy to wait for a later version. Do you have an approximate time frame for that? Would it be a couple of weeks, or more like a month+? Just trying to figure out if we should fork in the meantime.

Thanks for your reply and for looking into this!! I really appreciate it.

**Comment by owenpearson** [comment]
Hey @codegoalie,

That's good to know about how you were able to receive messages higher than the default message limit. I think you may be right about there being some compression. We will have to test the behaviour here and see if we can make the read limit correctly aligned with the message limit, otherwise we will just add a client option to configure the read limit manually.

In terms of time frames, I think it should take no longer than a couple of weeks, I hope that's okay 🙂

**Comment by codegoalie** [comment]
That sounds like a reasonable approach. No need to configure if there's a hard limit on the platform side.

We _may_ just fork at ~v1.2.12 and add a single commit to up the limit. We'd like to get going shortly. I'll keep an eye out here and we can see who wins the race ;)

Thanks so much!!

**Comment by sacOO7** [comment]
It seems compression has to do with https://github.com/nhooyr/websocket/blob/master/compress.go#L22.

**Comment by sacOO7** [comment]
Yes, @joshforbes we will so resolve and merge this one 👍

**Comment by sacOO7** [comment]
Hi @codegoalie @joshforbes we have created a new release v1.2.13 with a fix, please also refer to https://github.com/ably/ably-go#update-maxmessagesizeread-limit-for-realtime-message-subscription section for more information.

**Comment by codegoalie** [comment]
I was able to test the new version and it's working for us! 🎉 Thanks so much!

**Comment by sacOO7** [comment]
@codegoalie @joshforbes do star the repo. if not already :  )

Thanks!
