### ISSUE TITLE
Suspended connection goes to failed state on resume attempt

### ISSUE THREAD

**Issue by mclark-ably** [ably/ably-go#638]
Appears to be a regression since v1.2.15 where a clients connection fails when connectivity is restored after the client has gone to suspended state

```Realtime Connection: closed Connection event: FAILED state=FAILED reason=[ErrorInfo :invalid connectionKey: . (See https://help.ably.io/error/80018 for help.) code=80018 invalid connection id (invalid format) statusCode=400]```

in v1.2.14 this behaves as expected as per https://sdk.ably.com/builds/ably/specification/main/features/#RTN15g and https://sdk.ably.com/builds/ably/specification/main/features/#RTN15c

```
Connection event: CONNECTING state=CONNECTING reason=<nil>2024/05/13 12:04:42 [VERBOSE] Realtime Connection: received (action="connected", id="ruNl7HJn8g", details=&ably.connectionDetails{ClientID:"*", ConnectionKey:"108IqSz2gBbkBu!ruNl7HJn8giSf98t-13974b", MaxMessageSize:65536, MaxFrameSize:262144, MaxInboundRate:75, ConnectionStateTTL:120000000000, MaxIdleInterval:15000000000})
2024/05/13 12:04:42 [VERBOSE] connection readlimit set to 65536
Connection event: CONNECTED state=CONNECTED reason=[ErrorInfo :Unable to recover connection: not found (CqObEu_PIL6XXDjn) code=80008 unable to recover connection (connection expired) statusCode=400] See https://help.ably.io/error/80008

2024/05/13 12:04:57 [VERBOSE] Realtime Connection: received (action="heartbeat")
2024/05/13 12:05:12 [VERBOSE] Realtime Connection: received (action="heartbeat")
2024/05/13 12:05:27 [VERBOSE] Realtime Connection: received (action="heartbeat")
2024/05/13 12:05:42 [VERBOSE] Realtime Connection: received (action="heartbeat")
```

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4794) by [Unito](https://www.unito.io)

**Comment by VeskeR** [comment]
Copying steps to reproduce from [slack conversation](https://ably-real-time.slack.com/archives/CURL4U2FP/p1715600285879729):

> All I did was create a realtime connection, disconnect network for 2 minutes until connection state is suspended and then reconnect in both latest and 1.2.14. So a basic script with `_, err := ably.NewRealtime(ably.WithKey(<API_KEY>),ably.WithLogLevel(4))` can reproduce

It seems related to [no-connection-serial changes](https://github.com/ably/ably-go/issues/612) done in 1.2.15. We're working on a fix.

**Comment by sacOO7** [comment]
Looking into it, expect update by next week 👍
