### ISSUE TITLE
A synthetic leave does not trigger the presence event listener callback

### ISSUE THREAD

**Issue by mclark-ably** [ably/ably-go#646]
Consider the following basic example of a go client listening for all presence messages

```
_, err = channel.Presence.SubscribeAll(ctx, func(msg *ably.PresenceMessage) {
		fmt.Println("this is the msg", msg)
		fmt.Println("Agents: ")
		clients, err := channel.Presence.Get(ctx)
		if err != nil {
			panic(err)
		}
		for _, client := range clients {
			fmt.Println("Present client:\n", client)
		}
	})
```

When another client enters presence, the event listener callback is triggered

`2024/07/17 10:02:46 [VERBOSE] Realtime Connection: received (action="presence", id="hR2fpIIKRj", channel="my_channel", timestamp=1721206966861, presenceMessages=[<PresenceMessage enter clientID=another_client data=<nil>>])`

callback
`this is the msg <PresenceMessage enter clientID=another_client data=<nil>>
Agents: 
Present client:
 <PresenceMessage present clientID=another_client data=<nil>>`
 
When another client leaves the presence by call leave, the event listener callback is triggered

`2024/07/17 10:04:26 [VERBOSE] Realtime Connection: received (action="presence", id="hR2fpIIKRj", channel="my_channel", timestamp=1721207066146, presenceMessages=[<PresenceMessage leave clientID=another_client data=<nil>>])`

callback
`this is the msg <PresenceMessage leave clientID=another_client data=<nil>>
Agents: `

When another client leaves via a synthetic leave ( i.e a closed connection without explicitly calling leave) the callback is not triggered (there is no connectionId in the message)

`2024/07/17 10:06:48 [VERBOSE] Realtime Connection: received (action="presence", id="", channel="my_channel", timestamp=1721207208970, presenceMessages=[<PresenceMessage leave clientID=another_client data=<nil>>])`

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4877) by [Unito](https://www.unito.io)

**Comment by sacOO7** [comment]
@mclark-ably is this raised by customer ? And does this work on older versions of ably? Also, can you post code to reproduce the same ?

**Comment by mclark-ably** [comment]
@sacOO7 Yes from a customer issue. Seems to work in 1.2.14

**Comment by sacOO7** [comment]
Issue exist with the `msgpack` library used for encoding and decoding -> https://github.com/ugorji/go/tree/master/codec. 
Hence, issue exist in the library in older as well as new versions. Checking if updating `msgpack` lib to latest versions will fix the issue.

**Comment by sacOO7** [comment]
Current version `github.com/ugorji/go/codec v1.1.9`, is not able to decode 
```
hqZhY3Rpb24OomlkrGFaYnFaTWZmVFk6MKdjaGFubmVsp2NoYW5uZWytY2hhbm5lbFNlcmlhbNkmZTAycFNpZDdRQmVTWW0wODA5NTYwOEAxNzIxODMyNTk3MDY2LTCpdGltZXN0YW1wzwAAAZDlOGZKqHByZXNlbmNlkYWoY2xpZW50SWSnY2xpZW50Mqxjb25uZWN0aW9uSWSqZmZWalBZanlHQal0aW1lc3RhbXDPAAABkOU4ZkqkZGF0Ya1lbnRlciBjbGllbnQypmFjdGlvbgM=
```
properly. The proper decode for this base64 string can be found -> https://ref45638.github.io/msgpack-converter/

**Comment by sacOO7** [comment]
Seems related https://github.com/ugorji/go/issues/344
